// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUpPN3oa4NQ2wUnAK2vR6SwLgKrewsdvA',
    appId: '1:730208937654:web:edeca5f885385bcf982817',
    messagingSenderId: '730208937654',
    projectId: 'po1flutter',
    authDomain: 'po1flutter.firebaseapp.com',
    storageBucket: 'po1flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtw-iKCp6AUiNUiiaNM_z5-0V0IQieYM',
    appId: '1:730208937654:android:90eb46f58070297c982817',
    messagingSenderId: '730208937654',
    projectId: 'po1flutter',
    storageBucket: 'po1flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3HWbDka4ODndF8z3blz5_8uSkldOaZFY',
    appId: '1:730208937654:ios:50d0c7dde101b82e982817',
    messagingSenderId: '730208937654',
    projectId: 'po1flutter',
    storageBucket: 'po1flutter.appspot.com',
    iosBundleId: 'pt.isec.flutter2',
  );
}
