// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZCcXpFo0HYy76beUpUovmG4wSmhTJ0o',
    appId: '1:446211678100:web:7b60b600d525a064777981',
    messagingSenderId: '446211678100',
    projectId: 'p01flutterfb',
    authDomain: 'p01flutterfb.firebaseapp.com',
    storageBucket: 'p01flutterfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwsHG4g3kNfuqpIrX12vTwVaCza4WuQ2U',
    appId: '1:446211678100:android:86580e0dcca4bbc4777981',
    messagingSenderId: '446211678100',
    projectId: 'p01flutterfb',
    storageBucket: 'p01flutterfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeuWjyAXXB9302JlXVthlQg3SB2kb95p0',
    appId: '1:446211678100:ios:f0b40a8488366319777981',
    messagingSenderId: '446211678100',
    projectId: 'p01flutterfb',
    storageBucket: 'p01flutterfb.appspot.com',
    iosBundleId: 'com.example.pDoisFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeuWjyAXXB9302JlXVthlQg3SB2kb95p0',
    appId: '1:446211678100:ios:2d566a081ed3c82d777981',
    messagingSenderId: '446211678100',
    projectId: 'p01flutterfb',
    storageBucket: 'p01flutterfb.appspot.com',
    iosBundleId: 'com.example.pDoisFlutter.RunnerTests',
  );
}
